var topics = {
    "Fundamentals":[
        "Variables",
        "print",
        "input",
        "Strings",
        "Integers",
    ],
    "Math":[
        "Modulo",
        "Floor-Ceiling",
        "Trigonometry",
        "XY-Coordinates",
    ],
    "Lists-Arrays":[
        "Indexing",
        "For-Loops",
        "Append",
    ],
    "Scratch":[
        "Movement",
        ""
    ],
}