//Keys are categories, each with an array as value
//Value arrays contain individual bullet point topics
var topics = {
    "Fundamentals":[
        "Variables",
        "print()",
        "input()",
        "Strings",
        "Integers",
        "Booleans",
    ],
    "Logic":[
        "if / else",
        "elif",
        "Nested ifs",
        "and / or",
    ],
    "Math":[
        "Comparisons",
        "Modulo Operation",
        "Floor / Ceiling",
        "Trigonometry",
        "XY Coordinates",
    ],
    "Lists / Arrays":[
        "Indexing",
        "Append",
        "Item Assignment by Index",
        "Item Removal",
        "For Loops by Index",
        "For Loops by Element",
    ],
    "Loops":[
        "For Loops",
        "While Loops",
        "Nested Loops",
    ],
    "Functions":[
        "Parameters / Arguments",
        "Definition",
        "Recursion",
        "Lambda",
    ],
    "HTML":[
        "HTML Tags",
        "Headers",
        "Paragraphs",
        "Links",
        "Images",
        "Form Inputs",
        "Element IDs",
    ],
    "CSS":[
        "Selection by Tag Name",
        "Selection by ID / Class",
        "Color changes",
        "Adding borders",
        "Changing fonts",
        "Flexbox layouts",
    ],
    "Javascript":[
        "DOM Referencing",
        "Event Listeners",
        "Timing Functions",
        "forEach()",
    ],
    "Phaser CE":[
        "Gravity",
        "Groups",
        "Collision",
    ],
    "Tkinter":[
        "Creating a window",
        "Buttons",
        "Labels",
        "Text Entry",
    ],
    "Scratch":[
        "Movement",
        "Variables",
        "Ask/Answer",
        "Color Collsion",
        "Sprite Collision",
        "Gravity",
        "Messages",
        "Clones",
        "Forever Loops",
        "Repeat Until X Loops",
    ],
}