// ONLY ALPHABET AND DASHES
// NO SPACES
var topics = {
    "Fundamentals":[
        "Variables",
        "print",
        "input",
        "Strings",
        "Integers",
        "Booleans",
    ],
    "Logic":[
        "if-else",
        "and-or",
    ],
    "Math":[
        "Modulo",
        "Floor-Ceiling",
        "Trigonometry",
        "XY-Coordinates",
    ],
    "Lists-Arrays":[
        "Indexing",
        "Append",
    ],
    "Loops":[
        "For-Loops",
        "While-Loops",
        "Nested-Loops",
    ],
    "Functions":[
        "Definition",
        "Recursion",
    ],
    "HTML":[
        "Element-Creation",
        "Images",
        "Links",
        "Element-IDs",
    ],
    "CSS":[
        "Selection-by-Tag",
        "Selection-by-ID-Class",
        "Changing-colors",
        "Adding-borders",
        "Changing-fonts"
    ],
    "Javascript":[
        "DOM-Element-Selection",
        "Event-Listeners",
        "Timing-Functions",
        "forEach",
    ],
    "Scratch":[
        "Movement",
        "Variables",
        "Ask-Answer",
        "Gravity",
        "Messages",
        "Clones",
    ],
}